[build]
  functions = "dist/api"

[[redirects]]
  from = "/usecase-cainz/"
  to = "https://microcms.io/interviews/cainz"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-web-creator-box/"
  to = "https://microcms.io/interviews/web-creator-box"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-fuller/"
  to = "https://microcms.io/interviews/fuller"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-dip/"
  to = "https://microcms.io/interviews/dip"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-gree-x/"
  to = "https://microcms.io/interviews/gree-x"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-chunichi/"
  to = "https://microcms.io/interviews/chunichi"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-ymj/"
  to = "https://microcms.io/interviews/ymj"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-kinto/"
  to = "https://microcms.io/interviews/kinto"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-nifty/"
  to = "https://microcms.io/interviews/nifty"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-cerezo/"
  to = "https://microcms.io/interviews/cerezo"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-scrap/"
  to = "https://microcms.io/interviews/scrap"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-freee/"
  to = "https://microcms.io/interviews/freee"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-tokyo-gas/"
  to = "https://microcms.io/interviews/tokyo-gas"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-odx/"
  to = "https://microcms.io/interviews/odx"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-alba/"
  to = "https://microcms.io/interviews/alba"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-otamanabi-no-mori/"
  to = "https://microcms.io/interviews/otamanabi-no-mori"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-elnet/"
  to = "https://microcms.io/interviews/elnet"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-smarthr/"
  to = "https://microcms.io/interviews/smarthr"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-leact/"
  to = "https://microcms.io/interviews/leact"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-dmm/"
  to = "https://microcms.io/interviews/dmm"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-housmart/"
  to = "https://microcms.io/interviews/housmart"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-gvatech/"
  to = "https://microcms.io/interviews/gvatech"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-toridoll/"
  to = "https://microcms.io/interviews/toridoll"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-polimill/"
  to = "https://microcms.io/interviews/polimill"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-reiwatravel/"
  to = "https://microcms.io/interviews/reiwatravel"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-ndc/"
  to = "https://microcms.io/interviews/ndc"
  status = 301
  force = true

[[redirects]]
from = "/usecase-yamap-store/"
to = "https://microcms.io/interviews/yamap-store"
status = 301
force = true

[[redirects]]
  from = "/usecase-nrinetcom/"
  to = "https://microcms.io/interviews/nrinetcom"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-discoveryjapan/"
  to = "https://microcms.io/interviews/discoveryjapan"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-paconsul/"
  to = "https://microcms.io/interviews/paconsul"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-chikaku/"
  to = "https://microcms.io/interviews/chikaku"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-zozotech/"
  to = "https://microcms.io/interviews/zozotech"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-sgis/"
  to = "https://microcms.io/interviews/sgis"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-monex-am/"
  to = "https://microcms.io/interviews/monex-am"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-dwango/"
  to = "https://microcms.io/interviews/dwango"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-beatfit/"
  to = "https://microcms.io/interviews/beatfit"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-odakyu/"
  to = "https://microcms.io/interviews/odakyu"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-medley/"
  to = "https://microcms.io/interviews/medley"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-port/"
  to = "https://microcms.io/interviews/port"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-acall/"
  to = "https://microcms.io/interviews/acall"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-knockonthedoor/"
  to = "https://microcms.io/interviews/knockonthedoor"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-mediba/"
  to = "https://microcms.io/interviews/mediba"
  status = 301
  force = true

[[redirects]]
  from = "/crowdworks-with-microcms/"
  to = "https://microcms.io/interviews/crowdworks-with-microcms"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-mediano/"
  to = "https://microcms.io/interviews/mediano"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-konicaminolta/"
  to = "https://microcms.io/interviews/konicaminolta"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-rebuild/"
  to = "https://microcms.io/interviews/rebuild"
  status = 301
  force = true

[[redirects]]
  from = "/usecase-interspace/"
  to = "https://microcms.io/interviews/interspace"
  status = 301
  force = true

[[redirects]]
  from = "/microcms-multilingual-site/"
  to = "https://help.microcms.io/ja/knowledge/multilingual-site"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
