[build]
  functions = "dist/api"

[[redirects]]
  from = "/usecase-rebuild"
  to = "https://microcms.io/interviews/usecase-rebuild"
  status = 302

[[redirects]]
  from = "/usecase-rebuild/"
  to = "https://microcms.io/interviews/usecase-rebuild"
  status = 302

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404